<a href="https://colab.research.google.com/github/MattWroclaw/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


###Norma wektora, długość wektora w  przestrzeni R2 (nasza płaszczyzna)

Norma wektora to długość wektora, czyli pierwiastek z sumy kwadratów jego wpsółrzędnych

In [ ]:
#  tworzenie wektorów w bibliotece numpy
v1 = np.array([0,4])


In [ ]:
np.linalg.norm(v1)

4.0

In [ ]:
v2 = np.array([-3,30])
np.linalg.norm(v2)

30.14962686336267

Gdy jest więcej współrzędnych (Rn) to jest pierwiastek z sumy kwadratów wszystkich współrzędnych

In [ ]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

###Odległość dwóch punktów na płaszczyźnie

Jest to pierwiastek z sumy kwadratów różnic współrzędnych (początku i końca) wektora

In [ ]:
# mamy 2 punkty p i q
p = np.array([3,0])
q = np.array([0,4])


# liczymy odległość między tymi punktami
odl1 = np.linalg.norm(p-q)
odl1
odl2 = np.linalg.norm(q-p)
odl2

5.0

In [ ]:
# mamy 2 punkty p i q w przestrzeni R3
p = np.array([3,0, 1])
q = np.array([0,4 , 4])

np.linalg.norm(p-q)

5.830951894845301

###Mnożenie macierzy

Macierz A
m - wierszy
n - kolumn

Macierz B
n - wierszy
p - kolumn


Wspólny musi być parametr, że kolumny w A to tyle co wiersze w B

Liczba kolumn w Lewej macierzy = liczba wierszy w Prawej macierzy

NIe jest przemienne

X = \
|5,3|\
|3,9|

Y=\
| 1|\
|-1|

wynik będzie
|q|\
|w|

q = 5*1 + 3*(-1) =2\
w = 3*1 + 9*(-1) =-6

X*Y=\
| 2|\
|-6|





In [ ]:
X =  np.array([[5,3], [3,9]])
Y = np.array([[1] , [-1]])

print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
# mnożenie macierzy .dot()

Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

Mnożenie wiekszych macierzy
2x3
3x3

2 -1  3\
3  1  0


2  1  -1\
0 -1   2\
3  2   0

Wynik: \
q,w,e \
a,s,d


Można, bo liczba kolumn macierzy pierwszej = liczbie kolum macierzy w durgiej

Wiersze z lewej x Kolumny z prawej


In [ ]:
X = np.array([[2,-1,3], [3,1,0]])
Y = np.array([[2,1,-1], [0,-1,2], [3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


Rozmiar można oszacować: tyle i wierszy w 1 macierzy
tyle kolumn co w 2 macierzy

In [ ]:
np.dot(X,Y )

array([[13,  9, -4],
       [ 6,  2, -1]])

###Wyznacznik macierzy

Macierz ma tyle samo kolumn co wierszy,
jest n x n

|A|  <-- oznaczenie wyznacznika macierzy
det A <-- oznaczenie wyznacznika macierzy


det A =
1 2  
3 4

= 1*4  - 2*3


2. Macierz 3x3

Dla macierzy 3x3
A=(abcdefghi)
A=
​adg​beh​cfi​
​

Wyznacznik det⁡(A)det(A) można obliczyć używając rozwinięcia Laplace’a:
det⁡(A)=aei+bfg+cdh−ceg−bdi−afh
det(A)=aei+bfg+cdh−ceg−bdi−afh



In [ ]:
A = np.array([[2,4], [-1,3]])
np.linalg.det(A)

9.999999999999998

### Ślad macierzy

Macierz musi być kwadratowa.
Jest to suma elementó na przekątnej (lewy górny róg --> prawy dolny róg)

In [ ]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

### Macierz jednostokowa

Macierz kwadratowa;
wartości na przekątnej muszą =1

Lewy górny -> prawy dolny

Do generowania służy .eye(rozmiar, typ)

Domyślnie typ jest float

In [ ]:
np.eye(5 , dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Macierz odwrotna

Tylko macierz kwadratowa może mieć macież odwrotną.

A- macierz kwadratowa stopnia n. Macierz posiada macierz odwrotną gdy instniej macierz B taka że

AB=BA=I (I - macierz jednostkowa)

Macierz B nazywamy macierzą odwrotną.


In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
# Sprawdzenie: pomnożenie A*B powinno dać macierz jednostkową
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# sprawdzamy drugi warunek, czyli BA

np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

Zamiana wierszy na kolumny i kolumn na wiersze

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

###Rozwiązywanie układów równań

Mamy układ równań
a11 x1 + a12 x2 + ... + a1n xn = b1 \
a21 x1 + a22 x2 + ... + a2x xn = b2 \
...
am1 x1 + am2 x2 + ... + amn xn = bn

rozdzialamy to równanie na
* macierz współczynników
* macierz niewiadomych
* wektor wyrazów wolnych

zapisujemy to AX = B

Jeśli macierz układu A jest macierzą kwadratową to oznaczalność układu jest równoważna jej odwracalności, \
 AX=B \
A^-1 AX = A^-1B \
X = A^-1B \


Należy znaleźć macierz odwrotną do macierzy współczynników i pomnożyć ją przez wektor wyrazów wolnych.

In [4]:
#  2x + 4y = 10
#  x - y = -1

# x=1, y=2
A = np.array([[2,4], [1,-1]]) #macierz współczynników
B = np.array([[10], [-1]]) # wektor wyrazów wolnych
print(A, '\n')
print(B)


[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [5]:
#  obliczanie macierzy odwrotnej do A
A_iverse = np.linalg.inv(A)
A_iverse

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [6]:
X  = np.dot(A_iverse, B)
X

array([[1.],
       [2.]])