<a href="https://colab.research.google.com/github/MattWroclaw/data-science-bootcamp/blob/main/wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello wroclaw')

Hello wroclaw


In [3]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
dir(np)

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

###1D Array###

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
x.size

3

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2,2.10,3.4320])
print(x)

[1.2   2.1   3.432]


In [ ]:
x.dtype

dtype('float64')

###2D array##

In [ ]:
x = np.array([[1,2,3],[-4,5,-6]])

In [ ]:
x.ndim

2

In [ ]:
x.shape #wiersze x kol

(2, 3)

###3D Array###

In [ ]:
x = np.array([
    [[1,2,2] , [3,4,5]],
    [[6,7,8] , [9,10,11]],
    [[12,13,14] , [15,16,17]],
    [[18,19,20] , [21,22,23]]
]
)

In [ ]:
x.ndim

3

In [ ]:
x.shape

(4, 2, 3)

###Typy danych###

In [ ]:
A = np.array([1,2.0,3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype = 'float')
A.dtype
A

array([1., 2., 3.])

In [ ]:
A = np.array([1,2,3], dtype = 'complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.4984,2.797,3.00000000], dtype = 'int')
A.dtype
A

array([1, 2, 3])

In [ ]:
A = np.array([146,200,37], dtype = np.int8)
A.dtype

<ipython-input-14-7a000833eb04>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 146 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([146,200,37], dtype = np.int8)
<ipython-input-14-7a000833eb04>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([146,200,37], dtype = np.int8)


dtype('int8')

In [ ]:
A = np.array([146,200,37], dtype = np.uint8)
A.dtype

dtype('uint8')

###Tworzenie tablic###

In [ ]:
A = np.zeros(shape=(4,10))
A
# np.dtype

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape = (6,6), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arrange(10)

In [ ]:
np.arange(start=5, stop=26, step=5)

array([ 5, 10, 15, 20, 25])

In [ ]:
np.arange(start=100, stop=20, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30])

In [ ]:
np.arange(start=0, stop =1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

Elementy równo rozłożone w tablicy

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Zrobienie macierzy z  tablicy

In [ ]:
A = np.arange(18)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
A.reshape(2,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [ ]:
A.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

Chcemy mieć 3 wiersze, niech python sam wyliczy ile ma być kolumn --> wstawiamy -1

In [ ]:
A.reshape((3,-1))


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

Chcemy mieć 6 kolumn, ale nie wiemy ile to wierszy. Niech python to obliczy

In [ ]:
A.reshape((-1,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

###Podstawowe operacje na tablicach##

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


Dodawanie tablic. Rozmiar tablic musi się zgadzać

In [ ]:
A + B

array([6, 0, 7, 4])

Inne operacje algebraiczne. Element po elemencie

In [ ]:
print(A - B)
print(A * B)
print(A / B)

[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


Dodawanie stałej do wartości tablicy


In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

Dedykowane metody do prostych działań

In [ ]:
np.add(A,B)
np.subtract(A,B)
np.multiply(A,B)
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

Mnożenie macieżowe


In [ ]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


Zwykłe mnożenie A * B , to mnożenie element po elemencie. Ale to nie jest mnożenie macieży

In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

Żeby wykonać mnożenie macieży należy użyć .dot
Mnożymy wiersz razy kolumna i wiersz razy kolumna, tzn piwerwszy wyraz z 1 wiersza mnożymy przez pierwszy wyraz z 1 kolkumny; 2 wyr z pierwszego wiersza z 2 wyrazem z pierwszej kolumny; 3 wyraz z pierwszego rzędu mnożymy  z 3 wrazem z pierwszej kolumny.
Następnie wszystkie te iloczyny dodajemy

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

ten sam efekt X.dot(Y)

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

Uwaga, mnożenie macierzy nie jest przemienne!

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

Trzecia możliwość mnożenia macierzowego to symbol "@"

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

###Liczby pseudolosowe###


In [ ]:
np.random.seed(0)

Bez parametru to zwraca losową wartość z rozkładu normalnego
Średnia 0
odchylenie standardowe 1

In [ ]:
np.random.randn()

0.8681827216269559

In [ ]:
np.random.randn(10)

array([ 0.74363342,  0.90315743,  0.58175172, -0.81764463,  0.01508818,
       -0.60544498,  0.8021052 , -0.75589398,  0.69183262, -0.86134743])

Tablica z rozkładu normalnego
10 wierszy
4 komumny

In [ ]:
np.random.randn(10, 4)

array([[ 0.12908313, -0.71667958, -0.05062551, -0.03792195],
       [ 0.11302714,  0.71765318, -0.4869216 ,  1.33228997],
       [ 0.04146704, -1.11344932,  0.61009881,  0.11727958],
       [ 0.1164376 , -0.24188647,  0.66226936, -0.0520144 ],
       [-1.12676867, -0.49510848, -0.42920916,  0.01145625],
       [-0.18396779, -0.74013315, -1.12058634, -0.9173355 ],
       [-0.02470961, -1.77422233,  0.31713036,  0.6438324 ],
       [-0.34215208, -2.14668787,  0.62957404,  0.02374507],
       [ 2.09130006,  0.4574268 , -0.23647857, -1.40312672],
       [ 0.24470908, -0.21088057, -0.08515287, -0.66936116]])

Rozkład jednostajny na przedziale,
wartość losowa 0-1

In [ ]:
np.random.rand()

0.8918128244321337

In [ ]:
np.random.rand(10)

array([0.08612755, 0.16311117, 0.15350981, 0.37121847, 0.80128456,
       0.94845389, 0.94991501, 0.64900212, 0.04151637, 0.55201301])

In [ ]:
np.random.rand(10,2)

array([[0.63186663, 0.24824778],
       [0.56339833, 0.90255472],
       [0.69740824, 0.51309674],
       [0.10394864, 0.69505495],
       [0.15415192, 0.96768105],
       [0.20630817, 0.67604744],
       [0.5305353 , 0.75311728],
       [0.6527443 , 0.2077649 ],
       [0.90283562, 0.68167947],
       [0.88182025, 0.12933729]])

randint -> zwraca liczbę całkowitą

In [ ]:
np.random.randint(10)

0

In [ ]:
np.random.randint(low =10 , high = 101)

75

In [ ]:
np.random.randint(low =10 , high = 101, size =3)

array([87, 18, 54])

choice -> losowo wybiera element z obiektu iterowalnego, który przekażemy

In [ ]:
np.random.choice([1,80,468,65,32])

65

In [ ]:
np.random.choice(['a','b','c'])

'c'

shufle -> Tasowanie danych
Zmiana zachodzi na obiekcie, nie trzeba specjalnie przypisywać

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([5, 1, 9, 4, 0, 2, 3, 6, 8, 7])

###Podstawowe funkcje w bibliotece numpy###

exponent
oblicza wartość funkcji wykładniczej e^x, gdzie e to podstawa logarytmu naturalnego, czyli około 2.71828

Logarytm naturalny to logarytm o podstawie ee, gdzie ee jest liczbą Eulera, czyli około 2.71828. Logarytm naturalny liczby xx jest oznaczany jako ln⁡(x)ln(x) i definiowany jako taka liczba yy, dla której zachodzi równość:

ey=xey=x

Innymi słowy, logarytm naturalny odpowiada na pytanie: do jakiej potęgi trzeba podnieść liczbę ee, aby otrzymać xx?

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(10)

22026.465794806718

In [ ]:
np.sqrt(2)

1.4142135623730951

In [ ]:
.all -> iteruje po liście i zwraca czy każda wartość jest true

In [ ]:
np.all([1,-2,3])

True

In [ ]:
np.all([1,-2,0])

False

 	F/60163461/06/24

 	Jak chce sie sprawdzić czy w dużej ilości 0 znajduje się jakaś 1 korzystamy z .any()

In [ ]:
np.any([1,-2,0])

True

In [ ]:
bool(0)

False

Mamy jakiś rozkład normalny i chcemy zobaczyć która wartość jest największa. Korzystamy z .argmax()

.argmax() --> zwraca index liczby która jest największa


In [ ]:
A = np.random.rand(5)
A

array([0.78875404, 0.21175332, 0.57529719, 0.98242893, 0.99927059])

In [ ]:
np.argmax(A)

4

jak chcemy wartość tej liczby wyciąć z listy robimy tak

In [ ]:
A[np.argmax(A)]

0.9992705895331091

In [ ]:
A[np.argmin(A)]

0.211753320644411

sortowanie tablicy przez zwrócenie indexów

In [ ]:
np.argsort(A)

array([1, 2, 0, 3, 4])

Największa i najmniejsza wartość z tablicy
.min()
.max()

In [ ]:
np.max(A)

0.9992705895331091

In [ ]:
np.min(A)

0.211753320644411

Średnia

In [ ]:
np.mean(A)

0.7115008134998517

Odchylenie mediana

In [ ]:
np.median(A)

0.7887540370939018

Odchylenie standardowe

In [ ]:
np.std(A)

0.293421380687826

###Indexowanie, wycinanie###

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[indx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2:6]

array([2, 3, 4, 5])

In [ ]:
# indexowanie od końca

A[-1]

19

In [ ]:
A[-5]

15

In [ ]:
np.reshape(A, (4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# wycinanie konkretnego wiersza
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
#  wycinanie konkretnej kolumny
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
#  wycinanie przedostaniej kolumny
A[:,-2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# wycinanie koknretnego elementu: wiesz / kol
A[2,3]

13

In [ ]:
#  zwracanie fragmentu tablicy: zakres wiersza/ zakres kolumn
# 3 i 4 nie wchodzą
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

przepisywanie zmiennych wewnątrz tablicy

In [ ]:
A[1,3]= 100
A

NameError: name 'A' is not defined

###Iteracja po tablicach###

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
print(A)
print(type(A))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>


In [ ]:
for row in A:
  print(row[:3])


[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


Iterowanie po każdym elemencie

In [ ]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


###Zmiana rozmiaru tablic###

In [4]:
A = np.arange(20)
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Wypłaszczanie .ravel()

odwrotna do reshape()

In [5]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Zamiana wiersz <--> kolumna
kolumna <--> wiersz

A.T


In [7]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

###Maski logiczne

In [9]:
A = np.arange(start = -10, stop=10, step=0.5)
A


array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [12]:
#  chcemy mieć z tej tablicy 10 wierszy
A = A.reshape(10, -1)
A


array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

Czym są maski logiczne?
Chcemy sprawdzić w których miejscach są wartości ujemmne

In [13]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
#  chcemy wyciąć tylko te dane, które nas interesują, czyli >0
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
#  łączenie warunków

np.bitwise_and(A>-5, A<5)  # <--- to nam zwróci maskę

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
#  wycinamy te elementy które nas ineresują
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [19]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])